<a href="https://colab.research.google.com/github/xecon/github-upload/blob/master/001_Data_Cleaning_Solved.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# @title Login using your Workshop Account, so we can access the data
from google.colab import auth
from google.cloud import bigquery
from google.colab import data_table

project = 'ct-workshop-001' # Project ID inserted based on the query results selected to explore
location = 'EU' # Location inserted based on the query results selected to explore
client = bigquery.Client(project=project, location=location)
data_table.enable_dataframe_formatter()
auth.authenticate_user()

In [ ]:
%load_ext google.colab.data_table

In [ ]:
# prompt: get data from bigquery table ct-workshop-001.workshop_datasets.dummy_data

# @title Get the data
sql = """
SELECT * FROM `ct-workshop-001.workshop_datasets.dummy_data`
"""
df = client.query(sql).to_dataframe()
df

,Naam,Data engineering,Data analysis,Data Science,ML Engineering,Role,Work,Gender,Age
0,Person 2,0,1,0,0,IT Support Specialist,audit data access using Excel,M,23
1,Person 14,0,1,4,0,Data Engineer,build predictive models in Python,F,23
2,Person 24,0,0,1,0,DevOps Engineer,visualize data in TensorFlow,M,26
3,Person 7,2,1,0,0,BI Developer,deploy models to production with BigQuery,F,44
4,Person 13,2,1,2,0,IT Support Specialist,visualize data in Excel,F,55
5,Person 15,2,2,2,0,Software Developer,deploy models to production with Docker,M,36
6,Person 16,2,0,0,0,Data Engineer,write ETL scripts using Docker,x,37
7,Person 5,0,0,1,1,IT Support Specialist,troubleshoot issues using Excel,F,28
8,Person 11,0,0,1,1,IT Support Specialist,process data with BigQuery,F,27
9,Person 12,0,1,1,1,DPO,design dashboards in BigQuery,x,23
10,Person 22,0,1,1,1,DPO,deploy models to production with Python,X,20
11,Person 3,1,1,1,1,Project Manager,optimize workflows with IntelliJ,F,23
12,Person 10,1,0,1,1,ML Engineer,process data with Tableau,M,24
13,Person 17,1,2,2,1,IT Support Specialist,manage data pipelines with BigQuery,X,57
14,Person 21,1,1,0,1,Data Engineer,process data with Jira,F,29
15,Person 23,1,2,0,1,Data Scientist,design dashboards in BigQuery,X,50
16,Person 26,1,-1,3,1,I don't know,?,m,43
17,Person 24,1,1,0,1,Software Developer,troubleshoot issues using Jupyter Notebooks,x,61
18,Person 1,2,1,1,1,BI Developer,audit data access using DBT,F,37
19,Person 6,2,2,2,1,DPO,audit data access using DBT,F,52
20,Person 18,5,2,2,1,Data Engineer,design dashboards in IntelliJ,None,56
21,Person 4,1,2,0,2,Project Manager,write ETL scripts using AWS,M,42
22,Person 9,1,4,2,2,ML Engineer,analyze trends using Jira,X,63
23,Person 25,1,1,0,2,Software Developer,troubleshoot issues using Jupyter Notebook,X,61
24,Person 20,3,3,0,2,DevOps Engineer,manage data pipelines with Excel,M,48
25,Person 8,1,2,1,3,Data Engineer,audit data access using SQL Server,None,68
26,Person 19,2,0,1,3,Data Scientist,process data with Collibra,F,50

In [ ]:
# prompt: Rename all columns without spaces and make them lowercase, also rename naam to name

# Rename columns
new_columns = []
for col in df.columns:
    new_col = col.replace(" ", "_").lower()
    if new_col == 'naam':
        new_col = 'name'
    new_columns.append(new_col)

df.columns = new_columns
df

,name,data_engineering,data_analysis,data_science,ml_engineering,role,work,gender,age
0,Person 2,0,1,0,0,IT Support Specialist,audit data access using Excel,M,23
1,Person 14,0,1,4,0,Data Engineer,build predictive models in Python,F,23
2,Person 24,0,0,1,0,DevOps Engineer,visualize data in TensorFlow,M,26
3,Person 7,2,1,0,0,BI Developer,deploy models to production with BigQuery,F,44
4,Person 13,2,1,2,0,IT Support Specialist,visualize data in Excel,F,55
5,Person 15,2,2,2,0,Software Developer,deploy models to production with Docker,M,36
6,Person 16,2,0,0,0,Data Engineer,write ETL scripts using Docker,x,37
7,Person 5,0,0,1,1,IT Support Specialist,troubleshoot issues using Excel,F,28
8,Person 11,0,0,1,1,IT Support Specialist,process data with BigQuery,F,27
9,Person 12,0,1,1,1,DPO,design dashboards in BigQuery,x,23
10,Person 22,0,1,1,1,DPO,deploy models to production with Python,X,20
11,Person 3,1,1,1,1,Project Manager,optimize workflows with IntelliJ,F,23
12,Person 10,1,0,1,1,ML Engineer,process data with Tableau,M,24
13,Person 17,1,2,2,1,IT Support Specialist,manage data pipelines with BigQuery,X,57
14,Person 21,1,1,0,1,Data Engineer,process data with Jira,F,29
15,Person 23,1,2,0,1,Data Scientist,design dashboards in BigQuery,X,50
16,Person 26,1,-1,3,1,I don't know,?,m,43
17,Person 24,1,1,0,1,Software Developer,troubleshoot issues using Jupyter Notebooks,x,61
18,Person 1,2,1,1,1,BI Developer,audit data access using DBT,F,37
19,Person 6,2,2,2,1,DPO,audit data access using DBT,F,52
20,Person 18,5,2,2,1,Data Engineer,design dashboards in IntelliJ,None,56
21,Person 4,1,2,0,2,Project Manager,write ETL scripts using AWS,M,42
22,Person 9,1,4,2,2,ML Engineer,analyze trends using Jira,X,63
23,Person 25,1,1,0,2,Software Developer,troubleshoot issues using Jupyter Notebook,X,61
24,Person 20,3,3,0,2,DevOps Engineer,manage data pipelines with Excel,M,48
25,Person 8,1,2,1,3,Data Engineer,audit data access using SQL Server,None,68
26,Person 19,2,0,1,3,Data Scientist,process data with Collibra,F,50

# Cleaning

## Names

In [ ]:
# prompt: check if all names are unique

# Check for unique names
if len(df['name'].unique()) == len(df['name']):
    print("All names are unique.")
else:
    print("Not all names are unique.")
    duplicate_names = df[df.duplicated(subset=['name'], keep=False)]['name']
    print("Duplicate names:", duplicate_names.unique())

Not all names are unique.
Duplicate names: ['Person 24']

In [ ]:
# prompt: remove the first occurrence of the duplicate names

# Drop duplicates, keeping the first occurrence
df = df.drop_duplicates(subset=['name'], keep='first')

# Verify that there are no more duplicates
if len(df['name'].unique()) == len(df['name']):
    print("All names are now unique.")
else:
    print("There are still duplicate names.")
    duplicate_names = df[df.duplicated(subset=['name'], keep=False)]['name']
    print("Duplicate names:", duplicate_names.unique())

df

All names are now unique.

,name,data_engineering,data_analysis,data_science,ml_engineering,role,work,gender,age
0,Person 2,0,1,0,0,IT Support Specialist,audit data access using Excel,M,23
1,Person 14,0,1,4,0,Data Engineer,build predictive models in Python,F,23
2,Person 24,0,0,1,0,DevOps Engineer,visualize data in TensorFlow,M,26
3,Person 7,2,1,0,0,BI Developer,deploy models to production with BigQuery,F,44
4,Person 13,2,1,2,0,IT Support Specialist,visualize data in Excel,F,55
5,Person 15,2,2,2,0,Software Developer,deploy models to production with Docker,M,36
6,Person 16,2,0,0,0,Data Engineer,write ETL scripts using Docker,x,37
7,Person 5,0,0,1,1,IT Support Specialist,troubleshoot issues using Excel,F,28
8,Person 11,0,0,1,1,IT Support Specialist,process data with BigQuery,F,27
9,Person 12,0,1,1,1,DPO,design dashboards in BigQuery,x,23
10,Person 22,0,1,1,1,DPO,deploy models to production with Python,X,20
11,Person 3,1,1,1,1,Project Manager,optimize workflows with IntelliJ,F,23
12,Person 10,1,0,1,1,ML Engineer,process data with Tableau,M,24
13,Person 17,1,2,2,1,IT Support Specialist,manage data pipelines with BigQuery,X,57
14,Person 21,1,1,0,1,Data Engineer,process data with Jira,F,29
15,Person 23,1,2,0,1,Data Scientist,design dashboards in BigQuery,X,50
16,Person 26,1,-1,3,1,I don't know,?,m,43
18,Person 1,2,1,1,1,BI Developer,audit data access using DBT,F,37
19,Person 6,2,2,2,1,DPO,audit data access using DBT,F,52
20,Person 18,5,2,2,1,Data Engineer,design dashboards in IntelliJ,None,56
21,Person 4,1,2,0,2,Project Manager,write ETL scripts using AWS,M,42
22,Person 9,1,4,2,2,ML Engineer,analyze trends using Jira,X,63
23,Person 25,1,1,0,2,Software Developer,troubleshoot issues using Jupyter Notebook,X,61
24,Person 20,3,3,0,2,DevOps Engineer,manage data pipelines with Excel,M,48
25,Person 8,1,2,1,3,Data Engineer,audit data access using SQL Server,None,68
26,Person 19,2,0,1,3,Data Scientist,process data with Collibra,F,50

## Gender

In [ ]:
# prompt: capitalize the gender column, make sure values are in {X,M,F}, don't replace missing values

# Capitalize the 'gender' column
df['gender'] = df['gender'].str.upper()

# Ensure values are in {'X', 'M', 'F'}
def clean_gender(gender):
    if gender in ['X', 'M', 'F']:
        return gender
    else:
        return gender # Keep the original value if it's not in the set

df['gender'] = df['gender'].apply(clean_gender)

df

<ipython-input-60-526b3add58d6>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['gender'] = df['gender'].str.upper()
<ipython-input-60-526b3add58d6>:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['gender'] = df['gender'].apply(clean_gender)

,name,data_engineering,data_analysis,data_science,ml_engineering,role,work,gender,age
0,Person 2,0,1,0,0,IT Support Specialist,audit data access using Excel,M,23
1,Person 14,0,1,4,0,Data Engineer,build predictive models in Python,F,23
2,Person 24,0,0,1,0,DevOps Engineer,visualize data in TensorFlow,M,26
3,Person 7,2,1,0,0,BI Developer,deploy models to production with BigQuery,F,44
4,Person 13,2,1,2,0,IT Support Specialist,visualize data in Excel,F,55
5,Person 15,2,2,2,0,Software Developer,deploy models to production with Docker,M,36
6,Person 16,2,0,0,0,Data Engineer,write ETL scripts using Docker,X,37
7,Person 5,0,0,1,1,IT Support Specialist,troubleshoot issues using Excel,F,28
8,Person 11,0,0,1,1,IT Support Specialist,process data with BigQuery,F,27
9,Person 12,0,1,1,1,DPO,design dashboards in BigQuery,X,23
10,Person 22,0,1,1,1,DPO,deploy models to production with Python,X,20
11,Person 3,1,1,1,1,Project Manager,optimize workflows with IntelliJ,F,23
12,Person 10,1,0,1,1,ML Engineer,process data with Tableau,M,24
13,Person 17,1,2,2,1,IT Support Specialist,manage data pipelines with BigQuery,X,57
14,Person 21,1,1,0,1,Data Engineer,process data with Jira,F,29
15,Person 23,1,2,0,1,Data Scientist,design dashboards in BigQuery,X,50
16,Person 26,1,-1,3,1,I don't know,?,M,43
18,Person 1,2,1,1,1,BI Developer,audit data access using DBT,F,37
19,Person 6,2,2,2,1,DPO,audit data access using DBT,F,52
20,Person 18,5,2,2,1,Data Engineer,design dashboards in IntelliJ,None,56
21,Person 4,1,2,0,2,Project Manager,write ETL scripts using AWS,M,42
22,Person 9,1,4,2,2,ML Engineer,analyze trends using Jira,X,63
23,Person 25,1,1,0,2,Software Developer,troubleshoot issues using Jupyter Notebook,X,61
24,Person 20,3,3,0,2,DevOps Engineer,manage data pipelines with Excel,M,48
25,Person 8,1,2,1,3,Data Engineer,audit data access using SQL Server,None,68
26,Person 19,2,0,1,3,Data Scientist,process data with Collibra,F,50

In [ ]:
# prompt: replace missing values in the gender column with x

# Replace missing values in the 'gender' column with 'X'
df['gender'] = df['gender'].fillna('X')

df

<ipython-input-61-ee57ea056500>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['gender'] = df['gender'].fillna('X')

,name,data_engineering,data_analysis,data_science,ml_engineering,role,work,gender,age
0,Person 2,0,1,0,0,IT Support Specialist,audit data access using Excel,M,23
1,Person 14,0,1,4,0,Data Engineer,build predictive models in Python,F,23
2,Person 24,0,0,1,0,DevOps Engineer,visualize data in TensorFlow,M,26
3,Person 7,2,1,0,0,BI Developer,deploy models to production with BigQuery,F,44
4,Person 13,2,1,2,0,IT Support Specialist,visualize data in Excel,F,55
5,Person 15,2,2,2,0,Software Developer,deploy models to production with Docker,M,36
6,Person 16,2,0,0,0,Data Engineer,write ETL scripts using Docker,X,37
7,Person 5,0,0,1,1,IT Support Specialist,troubleshoot issues using Excel,F,28
8,Person 11,0,0,1,1,IT Support Specialist,process data with BigQuery,F,27
9,Person 12,0,1,1,1,DPO,design dashboards in BigQuery,X,23
10,Person 22,0,1,1,1,DPO,deploy models to production with Python,X,20
11,Person 3,1,1,1,1,Project Manager,optimize workflows with IntelliJ,F,23
12,Person 10,1,0,1,1,ML Engineer,process data with Tableau,M,24
13,Person 17,1,2,2,1,IT Support Specialist,manage data pipelines with BigQuery,X,57
14,Person 21,1,1,0,1,Data Engineer,process data with Jira,F,29
15,Person 23,1,2,0,1,Data Scientist,design dashboards in BigQuery,X,50
16,Person 26,1,-1,3,1,I don't know,?,M,43
18,Person 1,2,1,1,1,BI Developer,audit data access using DBT,F,37
19,Person 6,2,2,2,1,DPO,audit data access using DBT,F,52
20,Person 18,5,2,2,1,Data Engineer,design dashboards in IntelliJ,X,56
21,Person 4,1,2,0,2,Project Manager,write ETL scripts using AWS,M,42
22,Person 9,1,4,2,2,ML Engineer,analyze trends using Jira,X,63
23,Person 25,1,1,0,2,Software Developer,troubleshoot issues using Jupyter Notebook,X,61
24,Person 20,3,3,0,2,DevOps Engineer,manage data pipelines with Excel,M,48
25,Person 8,1,2,1,3,Data Engineer,audit data access using SQL Server,X,68
26,Person 19,2,0,1,3,Data Scientist,process data with Collibra,F,50

## Scores

In [ ]:
# prompt: Check that all scores in columns data_engineering	data_analysis	data_science	ml_engineering are between [0,3], print names that violate

import pandas as pd

# Assuming 'df' is your DataFrame from the previous code

def check_scores(df):
    """
    Checks if scores in specified columns are within the range [0, 3].

    Args:
        df: The input DataFrame.

    Returns:
        A DataFrame with names that violate the score constraint.
    """
    cols_to_check = ['data_engineering', 'data_analysis', 'data_science', 'ml_engineering']
    violations = []
    for index, row in df.iterrows():
        for col in cols_to_check:
            if not (0 <= row[col] <= 3):
                violations.append({'name': row['name'], 'column': col, 'score': row[col]})
    return pd.DataFrame(violations)

violations_df = check_scores(df)

if violations_df.empty:
    print("All scores are within the valid range [0, 3].")
else:
    print("The following names violate the score constraint:")
violations_df

The following names violate the score constraint:

        name            column  score
0  Person 14      data_science      4
1  Person 26     data_analysis     -1
2  Person 18  data_engineering      5
3   Person 9     data_analysis      4

In [ ]:
# prompt: Fix the violations of scores in data_engineering	data_analysis	data_science	ml_engineering, by bringing them to the min or max allowed value in [0,3]

# Assuming 'df' is your DataFrame from the previous code

def fix_scores(df):
    """
    Fixes scores in specified columns by bringing them to the min or max allowed value in [0, 3].

    Args:
        df: The input DataFrame.

    Returns:
        A DataFrame with fixed scores.
    """
    cols_to_check = ['data_engineering', 'data_analysis', 'data_science', 'ml_engineering']
    for index, row in df.iterrows():
        for col in cols_to_check:
            if row[col] < 0:
                df.loc[index, col] = 0
            elif row[col] > 3:
                df.loc[index, col] = 3
    return df

df = fix_scores(df)

# Verify that all scores are within the valid range
violations_df = check_scores(df)

if violations_df.empty:
    print("All scores are now within the valid range [0, 3].")
else:
    print("There are still scores outside the valid range:")
    print(violations_df)
df

All scores are now within the valid range [0, 3].

,name,data_engineering,data_analysis,data_science,ml_engineering,role,work,gender,age
0,Person 2,0,1,0,0,IT Support Specialist,audit data access using Excel,M,23
1,Person 14,0,1,3,0,Data Engineer,build predictive models in Python,F,23
2,Person 24,0,0,1,0,DevOps Engineer,visualize data in TensorFlow,M,26
3,Person 7,2,1,0,0,BI Developer,deploy models to production with BigQuery,F,44
4,Person 13,2,1,2,0,IT Support Specialist,visualize data in Excel,F,55
5,Person 15,2,2,2,0,Software Developer,deploy models to production with Docker,M,36
6,Person 16,2,0,0,0,Data Engineer,write ETL scripts using Docker,X,37
7,Person 5,0,0,1,1,IT Support Specialist,troubleshoot issues using Excel,F,28
8,Person 11,0,0,1,1,IT Support Specialist,process data with BigQuery,F,27
9,Person 12,0,1,1,1,DPO,design dashboards in BigQuery,X,23
10,Person 22,0,1,1,1,DPO,deploy models to production with Python,X,20
11,Person 3,1,1,1,1,Project Manager,optimize workflows with IntelliJ,F,23
12,Person 10,1,0,1,1,ML Engineer,process data with Tableau,M,24
13,Person 17,1,2,2,1,IT Support Specialist,manage data pipelines with BigQuery,X,57
14,Person 21,1,1,0,1,Data Engineer,process data with Jira,F,29
15,Person 23,1,2,0,1,Data Scientist,design dashboards in BigQuery,X,50
16,Person 26,1,0,3,1,I don't know,?,M,43
18,Person 1,2,1,1,1,BI Developer,audit data access using DBT,F,37
19,Person 6,2,2,2,1,DPO,audit data access using DBT,F,52
20,Person 18,3,2,2,1,Data Engineer,design dashboards in IntelliJ,X,56
21,Person 4,1,2,0,2,Project Manager,write ETL scripts using AWS,M,42
22,Person 9,1,3,2,2,ML Engineer,analyze trends using Jira,X,63
23,Person 25,1,1,0,2,Software Developer,troubleshoot issues using Jupyter Notebook,X,61
24,Person 20,3,3,0,2,DevOps Engineer,manage data pipelines with Excel,M,48
25,Person 8,1,2,1,3,Data Engineer,audit data access using SQL Server,X,68
26,Person 19,2,0,1,3,Data Scientist,process data with Collibra,F,50

## Name columns

In [ ]:
# prompt: split the name column into First name and Last name, by splitting on the last space

# Split the 'name' column into 'first_name' and 'last_name'
df[['first_name', 'last_name']] = df['name'].str.rsplit(' ', n=1, expand=True)

df

<ipython-input-64-ae20a0625ef3>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[['first_name', 'last_name']] = df['name'].str.rsplit(' ', n=1, expand=True)
<ipython-input-64-ae20a0625ef3>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[['first_name', 'last_name']] = df['name'].str.rsplit(' ', n=1, expand=True)

,name,data_engineering,data_analysis,data_science,ml_engineering,role,work,gender,age,first_name,last_name
0,Person 2,0,1,0,0,IT Support Specialist,audit data access using Excel,M,23,Person,2
1,Person 14,0,1,3,0,Data Engineer,build predictive models in Python,F,23,Person,14
2,Person 24,0,0,1,0,DevOps Engineer,visualize data in TensorFlow,M,26,Person,24
3,Person 7,2,1,0,0,BI Developer,deploy models to production with BigQuery,F,44,Person,7
4,Person 13,2,1,2,0,IT Support Specialist,visualize data in Excel,F,55,Person,13
5,Person 15,2,2,2,0,Software Developer,deploy models to production with Docker,M,36,Person,15
6,Person 16,2,0,0,0,Data Engineer,write ETL scripts using Docker,X,37,Person,16
7,Person 5,0,0,1,1,IT Support Specialist,troubleshoot issues using Excel,F,28,Person,5
8,Person 11,0,0,1,1,IT Support Specialist,process data with BigQuery,F,27,Person,11
9,Person 12,0,1,1,1,DPO,design dashboards in BigQuery,X,23,Person,12
10,Person 22,0,1,1,1,DPO,deploy models to production with Python,X,20,Person,22
11,Person 3,1,1,1,1,Project Manager,optimize workflows with IntelliJ,F,23,Person,3
12,Person 10,1,0,1,1,ML Engineer,process data with Tableau,M,24,Person,10
13,Person 17,1,2,2,1,IT Support Specialist,manage data pipelines with BigQuery,X,57,Person,17
14,Person 21,1,1,0,1,Data Engineer,process data with Jira,F,29,Person,21
15,Person 23,1,2,0,1,Data Scientist,design dashboards in BigQuery,X,50,Person,23
16,Person 26,1,0,3,1,I don't know,?,M,43,Person,26
18,Person 1,2,1,1,1,BI Developer,audit data access using DBT,F,37,Person,1
19,Person 6,2,2,2,1,DPO,audit data access using DBT,F,52,Person,6
20,Person 18,3,2,2,1,Data Engineer,design dashboards in IntelliJ,X,56,Person,18
21,Person 4,1,2,0,2,Project Manager,write ETL scripts using AWS,M,42,Person,4
22,Person 9,1,3,2,2,ML Engineer,analyze trends using Jira,X,63,Person,9
23,Person 25,1,1,0,2,Software Developer,troubleshoot issues using Jupyter Notebook,X,61,Person,25
24,Person 20,3,3,0,2,DevOps Engineer,manage data pipelines with Excel,M,48,Person,20
25,Person 8,1,2,1,3,Data Engineer,audit data access using SQL Server,X,68,Person,8
26,Person 19,2,0,1,3,Data Scientist,process data with Collibra,F,50,Person,19

In [ ]:
# prompt: Remove the name column and introduce put the first and last name columns in front

# Move 'first_name' and 'last_name' columns to the front
cols = ['first_name', 'last_name'] + [col for col in df.columns if col not in ['name', 'first_name', 'last_name']]
df = df[cols]

df

,first_name,last_name,data_engineering,data_analysis,data_science,ml_engineering,role,work,gender,age
0,Person,2,0,1,0,0,IT Support Specialist,audit data access using Excel,M,23
1,Person,14,0,1,3,0,Data Engineer,build predictive models in Python,F,23
2,Person,24,0,0,1,0,DevOps Engineer,visualize data in TensorFlow,M,26
3,Person,7,2,1,0,0,BI Developer,deploy models to production with BigQuery,F,44
4,Person,13,2,1,2,0,IT Support Specialist,visualize data in Excel,F,55
5,Person,15,2,2,2,0,Software Developer,deploy models to production with Docker,M,36
6,Person,16,2,0,0,0,Data Engineer,write ETL scripts using Docker,X,37
7,Person,5,0,0,1,1,IT Support Specialist,troubleshoot issues using Excel,F,28
8,Person,11,0,0,1,1,IT Support Specialist,process data with BigQuery,F,27
9,Person,12,0,1,1,1,DPO,design dashboards in BigQuery,X,23
10,Person,22,0,1,1,1,DPO,deploy models to production with Python,X,20
11,Person,3,1,1,1,1,Project Manager,optimize workflows with IntelliJ,F,23
12,Person,10,1,0,1,1,ML Engineer,process data with Tableau,M,24
13,Person,17,1,2,2,1,IT Support Specialist,manage data pipelines with BigQuery,X,57
14,Person,21,1,1,0,1,Data Engineer,process data with Jira,F,29
15,Person,23,1,2,0,1,Data Scientist,design dashboards in BigQuery,X,50
16,Person,26,1,0,3,1,I don't know,?,M,43
18,Person,1,2,1,1,1,BI Developer,audit data access using DBT,F,37
19,Person,6,2,2,2,1,DPO,audit data access using DBT,F,52
20,Person,18,3,2,2,1,Data Engineer,design dashboards in IntelliJ,X,56
21,Person,4,1,2,0,2,Project Manager,write ETL scripts using AWS,M,42
22,Person,9,1,3,2,2,ML Engineer,analyze trends using Jira,X,63
23,Person,25,1,1,0,2,Software Developer,troubleshoot issues using Jupyter Notebook,X,61
24,Person,20,3,3,0,2,DevOps Engineer,manage data pipelines with Excel,M,48
25,Person,8,1,2,1,3,Data Engineer,audit data access using SQL Server,X,68
26,Person,19,2,0,1,3,Data Scientist,process data with Collibra,F,50

## Add a new column

In [ ]:
# prompt: add a total_skill column that sums up data_engineering	data_analysis	data_science	ml_engineering

# Calculate the total skill score
df['total_skill'] = df['data_engineering'] + df['data_analysis'] + df['data_science'] + df['ml_engineering']

df

,first_name,last_name,data_engineering,data_analysis,data_science,ml_engineering,role,work,gender,age,total_skill
0,Person,2,0,1,0,0,IT Support Specialist,audit data access using Excel,M,23,1
1,Person,14,0,1,3,0,Data Engineer,build predictive models in Python,F,23,4
2,Person,24,0,0,1,0,DevOps Engineer,visualize data in TensorFlow,M,26,1
3,Person,7,2,1,0,0,BI Developer,deploy models to production with BigQuery,F,44,3
4,Person,13,2,1,2,0,IT Support Specialist,visualize data in Excel,F,55,5
5,Person,15,2,2,2,0,Software Developer,deploy models to production with Docker,M,36,6
6,Person,16,2,0,0,0,Data Engineer,write ETL scripts using Docker,X,37,2
7,Person,5,0,0,1,1,IT Support Specialist,troubleshoot issues using Excel,F,28,2
8,Person,11,0,0,1,1,IT Support Specialist,process data with BigQuery,F,27,2
9,Person,12,0,1,1,1,DPO,design dashboards in BigQuery,X,23,3
10,Person,22,0,1,1,1,DPO,deploy models to production with Python,X,20,3
11,Person,3,1,1,1,1,Project Manager,optimize workflows with IntelliJ,F,23,4
12,Person,10,1,0,1,1,ML Engineer,process data with Tableau,M,24,3
13,Person,17,1,2,2,1,IT Support Specialist,manage data pipelines with BigQuery,X,57,6
14,Person,21,1,1,0,1,Data Engineer,process data with Jira,F,29,3
15,Person,23,1,2,0,1,Data Scientist,design dashboards in BigQuery,X,50,4
16,Person,26,1,0,3,1,I don't know,?,M,43,5
18,Person,1,2,1,1,1,BI Developer,audit data access using DBT,F,37,5
19,Person,6,2,2,2,1,DPO,audit data access using DBT,F,52,7
20,Person,18,3,2,2,1,Data Engineer,design dashboards in IntelliJ,X,56,8
21,Person,4,1,2,0,2,Project Manager,write ETL scripts using AWS,M,42,5
22,Person,9,1,3,2,2,ML Engineer,analyze trends using Jira,X,63,8
23,Person,25,1,1,0,2,Software Developer,troubleshoot issues using Jupyter Notebook,X,61,4
24,Person,20,3,3,0,2,DevOps Engineer,manage data pipelines with Excel,M,48,8
25,Person,8,1,2,1,3,Data Engineer,audit data access using SQL Server,X,68,7
26,Person,19,2,0,1,3,Data Scientist,process data with Collibra,F,50,6

# Storing

In [ ]:
# prompt: Store the result in Bigquery in table ct-workshop-001.workshop_datasets.dummy_data_clean_ suffixed with today's date

from datetime import date

today = date.today().strftime("%Y%m%d")
# table_id = f"ct-workshop-001.workshop_datasets.dummy_data_clean_{today}"
usernr = 46 # @param {type:"integer"}
table_id = f"ct-workshop-001.workshop_workspace{usernr}.dummy_data_clean_{today}"

job_config = bigquery.LoadJobConfig(write_disposition="WRITE_TRUNCATE")

job = client.load_table_from_dataframe(
    df, table_id, job_config=job_config
)
job.result()  # Wait for the job to complete.

table = client.get_table(table_id)
print(
    "Loaded {} rows and {} columns to {}".format(
        table.num_rows, len(table.schema), table_id
    )
)

SyntaxError: invalid syntax (<ipython-input-1-43c9e017b33d>, line 7)